### ISSUE TITLE
How to enable strict ordering by default ?

### ISSUE THREAD

**Issue by teto** [bnprks/mcfly-fzf#7]
How to default to strict ordering ?
![image](https://github.com/bnprks/mcfly-fzf/assets/886074/588d2f8a-e41c-4b97-93f8-aa4418bc0f94)

I always end up enabling strict ordering but I couldn't find a MCFLY_ variable that does it.
sry if that's the wrong repo, was not sure wether to report here or mcfly

**Comment by bnprks** [comment]
Hi @teto, this is definitely the right repo for your issue. Now that you mention it I also have this problem since strict ordering is often what I want too. The rough solution will be to add the `--no-sort` option to the fzf call, which should cause it to start with strict ordering enabled.

I think you a can do this from the existing setup directly by setting `export FZF_CTRL_R_OPTS="--no-sort"` in your current shell or in your `.bashrc` or `.zshrc` file as appropriate.

I might add a more dedicated way to have this default to strict in the future, but this should tide you over for now.

**Comment by bnprks** [comment]
With release 0.1.3, I've now set this so strict ordering is the default (can be disabled by setting MCFLY_FZF_NO_STRICT_ORDERING), and the strict ordering toggle will be remembered

**Comment by teto** [comment]
ty !
